version: '3.8' 

services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8085:8080
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - zookeeper
      - kafka
       
